#index:
#    path: /
#    controller: App\Controller\DefaultController::index


user_dashboard:
    path: /user/dashboard
    controller: App\Controller\ProfileController::index
role_dashboard:
    path: /dashboard
    controller: App\Controller\RoleBasedProfileController::index


